# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cat mbti.json
          echo Add other actions to build,
          echo test, and deploy your project.

      # Build Process (빌드 작업)
      - name: Build Process
        run: |
          echo "Building now... "    # 빌드 작업 안내 문구 화면 출력
          mkdir build
          cp mbti.json build/
            # (빌드 정상 작동 X -> 테스트 작업에서 원하는 값이 나오지 않음)

      # Test Process (테스트 작업)
      - name: Test Process
        run: |
          echo "Testing now..."    # 테스트 작업 안내 문구 화면 출력
          test -f build/mbti.json

      # Github Pages :: Github 웹사이트 배포 서비스 제공
      # 결과물 Github pages 업로드
      - name: Upload Github pages
        uses: actions/upload-pages-artifact@v3    # GitHub Pages 결과물 업로드 (Action 사용)
        with:
          path: build    # build 디렉토리 결과물로 업로드

  deploy:
    needs: build    # "deploy 작업은 build 작업이 완료된 이후 수행한다."
                    # build 실행 중 오류 발생 -> deploy 실행 X
    runs-on: ubuntu-latest

    # Github pages 배포 권한 받기
    permissions:
      pages: write
      id-token: write

    environment:
      name: github pages

    steps:
    - name: Deploy Github pages
      uses: actions/deploy-pages@v4
      
